[Add] Github Actions workflow and the bash script to dynamically pull up Interfaces
[Resolved] conflicts in noxfile, parse, workflows and added new files like .py.j2

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -1,6 +1,7 @@
 name: Docker-Build Pipeline
 
 on:
+<<<<<<< HEAD
   push:
     branches:
       - main
@@ -46,3 +47,44 @@ jobs:
 
       - name: Verify the Gradio App
         run: curl http://localhost:8000
+=======
+    push:
+        branches:
+        - main
+    pull_request:
+        branches:
+        - main
+
+jobs:
+    build:
+        name: Docker Build
+        runs-on: ubuntu-latest
+
+        steps:
+        - name: Checkout Repository
+          uses: actions/checkout@v3
+
+        - name: Set up Python 3.10
+          uses: actions/setup-python@v3
+          with:
+            python-version: 3.10
+        
+        - name: Install nox
+          run: pip install nox
+
+        - name: Run parse,generate and build docker images
+          run: |
+            chmod +x ./scripts/build_docker.sh
+            ./scripts/build_docker.sh
+
+        - name: Run gradio Docker Container
+          run: |
+            docker run -d -p 8000:8000 --name gradio-container gradio-image
+            # Wait for the container to start
+            sleep 30
+            # Check if the container is running
+            curl --fail http://localhost:8000 || (echo "Failed to start the container" && exit 1)
+
+        - name: Verify the Gradio App
+          run: curl http://localhost:8000
+>>>>>>> f18e05f ([Add] Github Actions workflow and the bash script to dynamically pull up Interfaces)
