[see] workflow with amd64

diff --git a/.github/workflows/temp.yml b/.github/workflows/temp.yml
--- a/.github/workflows/temp.yml
+++ b/.github/workflows/temp.yml
@@ -15,3 +15,44 @@ jobs:
               run: |
                 echo "Runner architecture: $(uname -a)"
                 docker run --rm ubuntu:latest uname -a
+
+            - name: Checkout Repository
+              uses: actions/checkout@v3
+        
+            - name: Set up Python 3.9
+              uses: actions/setup-python@v3
+              with:
+                python-version: 3.9
+        
+            - name: Install nox
+              run: |
+                pip install nox
+                # TODO: remove this as a sessiond dependency
+                pip install pyyaml
+        
+            - name: Run parse,generate and build docker images
+              run: |
+                  chmod +x build_docker.sh
+                  ./build_docker.sh
+
+                  - name: Run gradio Docker Container
+                  run: |
+                    docker run -d -p 8000:7878 --name gradio-container gradio-image
+                    # Wait for the container to start
+                    sleep 30
+                    # Check if the container is running
+                    curl --fail http://localhost:8000 || (echo "Failed to start the container" && exit 1)
+          
+            - name: Verify the Gradio App
+              run: curl http://localhost:8000
+          
+            - name: Run Jupyter notebook
+              run: |
+                docker run -d -p 8888:7878 --name jupyter-container jupyter-image
+                # Wait for the container to start
+                sleep 30
+                # Check if the container is running
+                curl --fail http://localhost:8888 || (echo "Failed to start the container" && exit 1)
+                
+            - name: Verify the Jupyter Notebook
+              run: curl http://localhost:8888
