trying with amd64 - only threshold one

diff --git a/.github/workflows/temp.yml b/.github/workflows/temp.yml
--- a/.github/workflows/temp.yml
+++ b/.github/workflows/temp.yml
@@ -35,13 +35,13 @@ jobs:
                   chmod +x build_docker.sh
                   ./build_docker.sh
 
-                  - name: Run gradio Docker Container
-                  run: |
-                    docker run -d -p 8000:7878 --name gradio-container gradio-image
-                    # Wait for the container to start
-                    sleep 30
-                    # Check if the container is running
-                    curl --fail http://localhost:8000 || (echo "Failed to start the container" && exit 1)
+            - name: Run gradio Docker Container
+              run: |
+                docker run -d -p 8000:7878 --name gradio-container gradio-image
+                # Wait for the container to start
+                sleep 30
+                # Check if the container is running
+                curl --fail http://localhost:8000 || (echo "Failed to start the container" && exit 1)
           
             - name: Verify the Gradio App
               run: curl http://localhost:8000
